name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 98.92.114.55
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.BACKEND_EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            set -e
            cd /home/ubuntu
            docker compose down
            docker rm -f taskflow-backend || true
            docker compose up -d --build
